=== rare-magma/guitos/docs/guitos-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "expenses": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number"
                },
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": ["id", "name", "value"]
            }
          },
          "total": {
            "type": "number"
          }
        }
      },
      "incomes": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number"
                },
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": ["id", "name", "value"]
            }
          },
          "total": {
            "type": "number"
          }
        }
      },
      "stats": {
        "type": "object",
        "properties": {
          "available": {
            "type": "number"
          },
          "withGoal": {
            "type": "number"
          },
          "saved": {
            "type": "number"
          },
          "goal": {
            "type": "number"
          },
          "reserves": {
            "type": "number"
          }
        }
      }
    },
    "required": ["id", "name", "expenses", "incomes", "stats"]
  }
}

=== rare-magma/guitos/docs/guitos-sample.json
[
  {
    "id": "20c9542a-6876-40a9-a3d7-f42f17ba8a0b",
    "name": "2023-06",
    "expenses": {
      "items": [
        { "id": 1, "name": "rent", "value": 300 },
        { "id": 2, "name": "groceries", "value": 100 },
        { "id": 3, "name": "electricity", "value": 50 },
        { "id": 4, "name": "internet", "value": 30 },
        { "id": 5, "name": "gym", "value": 25 },
        { "id": 6, "name": "water", "value": 15 },
        { "id": 7, "name": "cellphone", "value": 20 },
        { "id": 8, "name": "coffee", "value": 10 }
      ],
      "total": 550
    },
    "incomes": {
      "items": [
        { "id": 1, "name": "salary", "value": 1000 },
        { "id": 2, "name": "2nd hand sale", "value": 50 }
      ],
      "total": 1050
    },
    "stats": {
      "available": 500,
      "withGoal": 395,
      "saved": 105,
      "goal": 10,
      "reserves": 1000
    }
  },
  {
    "id": "872115fd-48ed-4890-ad75-716ee9539943",
    "name": "2023-07",
    "expenses": {
      "items": [
        { "id": 1, "name": "rent", "value": 300 },
        { "id": 2, "name": "groceries", "value": 100 },
        { "id": 3, "name": "electricity", "value": 50 },
        { "id": 4, "name": "internet", "value": 30 },
        { "id": 5, "name": "gym", "value": 25 },
        { "id": 6, "name": "water", "value": 15 },
        { "id": 7, "name": "cellphone", "value": 20 },
        { "id": 8, "name": "coffee", "value": 10 },
        { "id": 9, "name": "car rental", "value": 200 }
      ],
      "total": 750
    },
    "incomes": {
      "items": [
        { "id": 1, "name": "salary", "value": 1000 },
        { "id": 2, "name": "2nd hand sale", "value": 250 }
      ],
      "total": 1250
    },
    "stats": {
      "available": 500,
      "withGoal": 375,
      "saved": 125,
      "goal": 10,
      "reserves": 1125
    }
  },
  {
    "id": "2896e048-3ac9-440b-847a-c0897197a444",
    "name": "2023-08",
    "expenses": {
      "items": [
        { "id": 1, "name": "rent", "value": 300 },
        { "id": 2, "name": "groceries", "value": 100 },
        { "id": 3, "name": "electricity", "value": 50 },
        { "id": 4, "name": "internet", "value": 30 },
        { "id": 5, "name": "gym", "value": 25 },
        { "id": 6, "name": "water", "value": 15 },
        { "id": 7, "name": "cellphone", "value": 20 },
        { "id": 8, "name": "coffee", "value": 10 },
        { "id": 9, "name": "car rental", "value": 200 },
        { "id": 10, "name": "bike rental", "value": 100 }
      ],
      "total": 850
    },
    "incomes": {
      "items": [
        { "id": 1, "name": "salary", "value": 1000 },
        { "id": 2, "name": "2nd hand sale", "value": 250 },
        { "id": 3, "name": "2nd hand sale", "value": 250 }
      ],
      "total": 1500
    },
    "stats": {
      "available": 650,
      "withGoal": 350,
      "saved": 300,
      "goal": 20,
      "reserves": 1125
    }
  }
]
